import firebase_admin
from firebase_admin import credentials, firestore

cred = credentials.Certificate('serviceAccountKey.json')
firebase_admin.initialize_app(cred)
db = firestore.client()

dishes = [

  # BREAKFAST
  {
    'name': 'Nasi Lemak',
    'category': 'Main Course',
    'mealServiceCategory': 'Breakfast',
    'price': 6.50, 'costPrice': 3.00, 'targetProfitMargin': 53.8,
    'nutrition': {'calories': 644.0, 'protein': 17.0, 'fiber': 3.0, 'carbs': 80.0, 'fat': 28.0, 'notes': 'Contains peanuts and anchovies'},
    'imageUrl': '', 'arModelUrl': '', 'isAvailable': True, 'recipe': {},
  },
  {
    'name': 'Roti Canai',
    'category': 'Appetizer',
    'mealServiceCategory': 'Breakfast',
    'price': 3.00, 'costPrice': 1.00, 'targetProfitMargin': 66.7,
    'nutrition': {'calories': 301.0, 'protein': 5.5, 'fiber': 1.5, 'carbs': 42.0, 'fat': 12.0, 'notes': 'Served with dhal and sambal'},
    'imageUrl': '', 'arModelUrl': '', 'isAvailable': True, 'recipe': {},
  },
  {
    'name': 'Mee Goreng Mamak',
    'category': 'Main Course',
    'mealServiceCategory': 'Breakfast',
    'price': 7.00, 'costPrice': 3.50, 'targetProfitMargin': 50.0,
    'nutrition': {'calories': 520.0, 'protein': 18.0, 'fiber': 2.5, 'carbs': 72.0, 'fat': 16.0, 'notes': 'Spicy stir-fried noodles'},
    'imageUrl': '', 'arModelUrl': '', 'isAvailable': True, 'recipe': {},
  },
  {
    'name': 'Nasi Goreng Kampung',
    'category': 'Main Course',
    'mealServiceCategory': 'Breakfast',
    'price': 8.00, 'costPrice': 4.00, 'targetProfitMargin': 50.0,
    'nutrition': {'calories': 568.0, 'protein': 20.0, 'fiber': 2.0, 'carbs': 78.0, 'fat': 18.0, 'notes': 'Village-style fried rice with egg'},
    'imageUrl': '', 'arModelUrl': '', 'isAvailable': True, 'recipe': {},
  },
  {
    'name': 'Teh Tarik',
    'category': 'Beverage',
    'mealServiceCategory': 'Breakfast',
    'price': 3.50, 'costPrice': 0.80, 'targetProfitMargin': 77.1,
    'nutrition': {'calories': 130.0, 'protein': 3.5, 'fiber': 0.0, 'carbs': 22.0, 'fat': 3.5, 'notes': 'Pulled milk tea'},
    'imageUrl': '', 'arModelUrl': '', 'isAvailable': True, 'recipe': {},
  },
  {
    'name': 'Kopi O Ais',
    'category': 'Beverage',
    'mealServiceCategory': 'Breakfast',
    'price': 2.50, 'costPrice': 0.60, 'targetProfitMargin': 76.0,
    'nutrition': {'calories': 45.0, 'protein': 0.5, 'fiber': 0.0, 'carbs': 10.0, 'fat': 0.0, 'notes': 'Black coffee with ice'},
    'imageUrl': '', 'arModelUrl': '', 'isAvailable': True, 'recipe': {},
  },
  {
    'name': 'Half Boiled Eggs',
    'category': 'Side Dish',
    'mealServiceCategory': 'Breakfast',
    'price': 2.50, 'costPrice': 0.80, 'targetProfitMargin': 68.0,
    'nutrition': {'calories': 140.0, 'protein': 12.0, 'fiber': 0.0, 'carbs': 1.0, 'fat': 10.0, 'notes': '2 eggs with soy sauce and pepper'},
    'imageUrl': '', 'arModelUrl': '', 'isAvailable': True, 'recipe': {},
  },
  {
    'name': 'Kaya Toast',
    'category': 'Appetizer',
    'mealServiceCategory': 'Breakfast',
    'price': 4.00, 'costPrice': 1.50, 'targetProfitMargin': 62.5,
    'nutrition': {'calories': 280.0, 'protein': 6.0, 'fiber': 1.5, 'carbs': 40.0, 'fat': 10.0, 'notes': 'Toast with coconut jam and butter'},
    'imageUrl': '', 'arModelUrl': '', 'isAvailable': True, 'recipe': {},
  },
  {
    'name': 'Bubur Ayam',
    'category': 'Main Course',
    'mealServiceCategory': 'Breakfast',
    'price': 6.00, 'costPrice': 2.50, 'targetProfitMargin': 58.3,
    'nutrition': {'calories': 310.0, 'protein': 22.0, 'fiber': 1.0, 'carbs': 42.0, 'fat': 5.0, 'notes': 'Chicken congee with ginger'},
    'imageUrl': '', 'arModelUrl': '', 'isAvailable': True, 'recipe': {},
  },
  {
    'name': 'Milo Ais',
    'category': 'Beverage',
    'mealServiceCategory': 'Breakfast',
    'price': 3.50, 'costPrice': 0.90, 'targetProfitMargin': 74.3,
    'nutrition': {'calories': 180.0, 'protein': 4.0, 'fiber': 0.5, 'carbs': 32.0, 'fat': 3.0, 'notes': 'Iced chocolate malt drink'},
    'imageUrl': '', 'arModelUrl': '', 'isAvailable': True, 'recipe': {},
  },

  # LUNCH
  {
    'name': 'Nasi Campur',
    'category': 'Main Course',
    'mealServiceCategory': 'Lunch',
    'price': 9.00, 'costPrice': 4.50, 'targetProfitMargin': 50.0,
    'nutrition': {'calories': 720.0, 'protein': 28.0, 'fiber': 4.0, 'carbs': 90.0, 'fat': 22.0, 'notes': 'Mixed rice with 3 side dishes'},
    'imageUrl': '', 'arModelUrl': '', 'isAvailable': True, 'recipe': {},
  },
  {
    'name': 'Chicken Rice',
    'category': 'Main Course',
    'mealServiceCategory': 'Lunch',
    'price': 8.50, 'costPrice': 4.00, 'targetProfitMargin': 52.9,
    'nutrition': {'calories': 610.0, 'protein': 35.0, 'fiber': 1.5, 'carbs': 75.0, 'fat': 14.0, 'notes': 'Served with chili sauce and soup'},
    'imageUrl': '', 'arModelUrl': '', 'isAvailable': True, 'recipe': {},
  },
  {
    'name': 'Grilled Fish',
    'category': 'Main Course',
    'mealServiceCategory': 'Lunch',
    'price': 15.00, 'costPrice': 7.00, 'targetProfitMargin': 53.3,
    'nutrition': {'calories': 380.0, 'protein': 42.0, 'fiber': 0.5, 'carbs': 8.0, 'fat': 18.0, 'notes': 'Whole fish grilled with sambal'},
    'imageUrl': '',
    'arModelUrl': 'https://raenhart11.github.io/restaurant-ar-models/grilled-fish.glb',
    'isAvailable': True, 'recipe': {},
  },
  {
    'name': 'Char Kuey Teow',
    'category': 'Main Course',
    'mealServiceCategory': 'Lunch',
    'price': 9.00, 'costPrice': 4.00, 'targetProfitMargin': 55.6,
    'nutrition': {'calories': 660.0, 'protein': 22.0, 'fiber': 2.0, 'carbs': 85.0, 'fat': 24.0, 'notes': 'Contains cockles and soy sauce'},
    'imageUrl': '', 'arModelUrl': '', 'isAvailable': True, 'recipe': {},
  },
  {
    'name': 'Asam Laksa',
    'category': 'Main Course',
    'mealServiceCategory': 'Lunch',
    'price': 8.00, 'costPrice': 3.50, 'targetProfitMargin': 56.3,
    'nutrition': {'calories': 410.0, 'protein': 20.0, 'fiber': 3.0, 'carbs': 62.0, 'fat': 8.0, 'notes': 'Sour fish noodle soup'},
    'imageUrl': '', 'arModelUrl': '', 'isAvailable': True, 'recipe': {},
  },
  {
    'name': 'Tom Yam Soup',
    'category': 'Appetizer',
    'mealServiceCategory': 'Lunch',
    'price': 10.00, 'costPrice': 4.50, 'targetProfitMargin': 55.0,
    'nutrition': {'calories': 180.0, 'protein': 15.0, 'fiber': 2.0, 'carbs': 12.0, 'fat': 7.0, 'notes': 'Spicy Thai prawn soup'},
    'imageUrl': '', 'arModelUrl': '', 'isAvailable': True, 'recipe': {},
  },
  {
    'name': 'Fresh Lime Juice',
    'category': 'Beverage',
    'mealServiceCategory': 'Lunch',
    'price': 4.00, 'costPrice': 1.00, 'targetProfitMargin': 75.0,
    'nutrition': {'calories': 60.0, 'protein': 0.5, 'fiber': 0.0, 'carbs': 14.0, 'fat': 0.0, 'notes': 'Freshly squeezed with sugar'},
    'imageUrl': '', 'arModelUrl': '', 'isAvailable': True, 'recipe': {},
  },
  {
    'name': 'Steamed White Rice',
    'category': 'Side Dish',
    'mealServiceCategory': 'Lunch',
    'price': 1.50, 'costPrice': 0.40, 'targetProfitMargin': 73.3,
    'nutrition': {'calories': 206.0, 'protein': 4.3, 'fiber': 0.6, 'carbs': 45.0, 'fat': 0.4, 'notes': 'Plain steamed jasmine rice'},
    'imageUrl': '', 'arModelUrl': '', 'isAvailable': True, 'recipe': {},
  },
  {
    'name': 'Ayam Goreng',
    'category': 'Main Course',
    'mealServiceCategory': 'Lunch',
    'price': 8.00, 'costPrice': 3.50, 'targetProfitMargin': 56.3,
    'nutrition': {'calories': 490.0, 'protein': 38.0, 'fiber': 0.0, 'carbs': 12.0, 'fat': 32.0, 'notes': 'Malay-style crispy fried chicken'},
    'imageUrl': '', 'arModelUrl': '', 'isAvailable': True, 'recipe': {},
  },
  {
    'name': 'Curry Puff',
    'category': 'Appetizer',
    'mealServiceCategory': 'Lunch',
    'price': 3.50, 'costPrice': 1.20, 'targetProfitMargin': 65.7,
    'nutrition': {'calories': 260.0, 'protein': 5.0, 'fiber': 1.5, 'carbs': 30.0, 'fat': 13.0, 'notes': 'Pastry filled with curried potato'},
    'imageUrl': '', 'arModelUrl': '', 'isAvailable': True, 'recipe': {},
  },

  # DINNER
  {
    'name': 'Grilled Chicken',
    'category': 'Main Course',
    'mealServiceCategory': 'Dinner',
    'price': 16.00, 'costPrice': 7.00, 'targetProfitMargin': 56.3,
    'nutrition': {'calories': 520.0, 'protein': 52.0, 'fiber': 0.0, 'carbs': 5.0, 'fat': 30.0, 'notes': 'Half chicken with herb marinade'},
    'imageUrl': '',
    'arModelUrl': 'https://raenhart11.github.io/restaurant-ar-models/chicken-meal.glb',
    'isAvailable': True, 'recipe': {},
  },
  {
    'name': 'Butter Prawns',
    'category': 'Main Course',
    'mealServiceCategory': 'Dinner',
    'price': 22.00, 'costPrice': 11.00, 'targetProfitMargin': 50.0,
    'nutrition': {'calories': 480.0, 'protein': 35.0, 'fiber': 0.5, 'carbs': 10.0, 'fat': 32.0, 'notes': 'Prawns with butter and curry leaves'},
    'imageUrl': '', 'arModelUrl': '', 'isAvailable': True, 'recipe': {},
  },
  {
    'name': 'Black Pepper Beef',
    'category': 'Main Course',
    'mealServiceCategory': 'Dinner',
    'price': 20.00, 'costPrice': 10.00, 'targetProfitMargin': 50.0,
    'nutrition': {'calories': 560.0, 'protein': 45.0, 'fiber': 1.5, 'carbs': 18.0, 'fat': 34.0, 'notes': 'Sirloin with black pepper sauce'},
    'imageUrl': '', 'arModelUrl': '', 'isAvailable': True, 'recipe': {},
  },
  {
    'name': 'Stir Fry Vegetables',
    'category': 'Side Dish',
    'mealServiceCategory': 'Dinner',
    'price': 7.00, 'costPrice': 2.50, 'targetProfitMargin': 64.3,
    'nutrition': {'calories': 120.0, 'protein': 4.0, 'fiber': 5.0, 'carbs': 14.0, 'fat': 5.0, 'notes': 'Seasonal greens with oyster sauce'},
    'imageUrl': '', 'arModelUrl': '', 'isAvailable': True, 'recipe': {},
  },
  {
    'name': 'Seafood Fried Rice',
    'category': 'Main Course',
    'mealServiceCategory': 'Dinner',
    'price': 13.00, 'costPrice': 6.00, 'targetProfitMargin': 53.8,
    'nutrition': {'calories': 620.0, 'protein': 28.0, 'fiber': 2.0, 'carbs': 80.0, 'fat': 18.0, 'notes': 'With prawns, squid and egg'},
    'imageUrl': '', 'arModelUrl': '', 'isAvailable': True, 'recipe': {},
  },
  {
    'name': 'Rendang Chicken',
    'category': 'Main Course',
    'mealServiceCategory': 'Dinner',
    'price': 14.00, 'costPrice': 6.50, 'targetProfitMargin': 53.6,
    'nutrition': {'calories': 490.0, 'protein': 40.0, 'fiber': 2.5, 'carbs': 15.0, 'fat': 28.0, 'notes': 'Slow-cooked dry curry'},
    'imageUrl': '', 'arModelUrl': '', 'isAvailable': True, 'recipe': {},
  },
  {
    'name': 'Sambal Sotong',
    'category': 'Main Course',
    'mealServiceCategory': 'Dinner',
    'price': 16.00, 'costPrice': 7.50, 'targetProfitMargin': 53.1,
    'nutrition': {'calories': 320.0, 'protein': 30.0, 'fiber': 2.0, 'carbs': 18.0, 'fat': 14.0, 'notes': 'Squid in spicy sambal paste'},
    'imageUrl': '', 'arModelUrl': '', 'isAvailable': True, 'recipe': {},
  },
  {
    'name': 'Coconut Shake',
    'category': 'Beverage',
    'mealServiceCategory': 'Dinner',
    'price': 6.00, 'costPrice': 2.00, 'targetProfitMargin': 66.7,
    'nutrition': {'calories': 220.0, 'protein': 2.0, 'fiber': 1.5, 'carbs': 28.0, 'fat': 12.0, 'notes': 'Fresh coconut blended with ice cream'},
    'imageUrl': '', 'arModelUrl': '', 'isAvailable': True, 'recipe': {},
  },
  {
    'name': 'Garlic Bread',
    'category': 'Appetizer',
    'mealServiceCategory': 'Dinner',
    'price': 5.00, 'costPrice': 1.80, 'targetProfitMargin': 64.0,
    'nutrition': {'calories': 200.0, 'protein': 4.5, 'fiber': 1.0, 'carbs': 28.0, 'fat': 8.0, 'notes': 'Toasted with garlic butter'},
    'imageUrl': '', 'arModelUrl': '', 'isAvailable': True, 'recipe': {},
  },
  {
    'name': 'Oxtail Soup',
    'category': 'Appetizer',
    'mealServiceCategory': 'Dinner',
    'price': 12.00, 'costPrice': 5.50, 'targetProfitMargin': 54.2,
    'nutrition': {'calories': 340.0, 'protein': 32.0, 'fiber': 1.0, 'carbs': 10.0, 'fat': 18.0, 'notes': 'Slow braised with spices'},
    'imageUrl': '', 'arModelUrl': '', 'isAvailable': True, 'recipe': {},
  },

  # DESSERT
  {
    'name': 'Cendol',
    'category': 'Dessert',
    'mealServiceCategory': 'Dessert',
    'price': 5.00, 'costPrice': 1.50, 'targetProfitMargin': 70.0,
    'nutrition': {'calories': 310.0, 'protein': 3.0, 'fiber': 1.0, 'carbs': 62.0, 'fat': 6.0, 'notes': 'With coconut milk and palm sugar'},
    'imageUrl': '', 'arModelUrl': '', 'isAvailable': True, 'recipe': {},
  },
  {
    'name': 'Ais Kacang',
    'category': 'Dessert',
    'mealServiceCategory': 'Dessert',
    'price': 5.50, 'costPrice': 1.80, 'targetProfitMargin': 67.3,
    'nutrition': {'calories': 280.0, 'protein': 5.0, 'fiber': 4.0, 'carbs': 58.0, 'fat': 4.0, 'notes': 'Shaved ice with red beans and syrup'},
    'imageUrl': '', 'arModelUrl': '', 'isAvailable': True, 'recipe': {},
  },
  {
    'name': 'Mango Pudding',
    'category': 'Dessert',
    'mealServiceCategory': 'Dessert',
    'price': 6.00, 'costPrice': 2.00, 'targetProfitMargin': 66.7,
    'nutrition': {'calories': 240.0, 'protein': 4.0, 'fiber': 1.5, 'carbs': 42.0, 'fat': 6.0, 'notes': 'Chilled with evaporated milk'},
    'imageUrl': '', 'arModelUrl': '', 'isAvailable': True, 'recipe': {},
  },
  {
    'name': 'Pisang Goreng',
    'category': 'Dessert',
    'mealServiceCategory': 'Dessert',
    'price': 4.00, 'costPrice': 1.20, 'targetProfitMargin': 70.0,
    'nutrition': {'calories': 300.0, 'protein': 2.5, 'fiber': 2.0, 'carbs': 48.0, 'fat': 11.0, 'notes': 'Crispy battered banana fritters'},
    'imageUrl': '', 'arModelUrl': '', 'isAvailable': True, 'recipe': {},
  },
  {
    'name': 'Ice Cream 2 Scoops',
    'category': 'Dessert',
    'mealServiceCategory': 'Dessert',
    'price': 7.00, 'costPrice': 2.50, 'targetProfitMargin': 64.3,
    'nutrition': {'calories': 360.0, 'protein': 6.0, 'fiber': 0.5, 'carbs': 50.0, 'fat': 14.0, 'notes': 'Choice of vanilla, chocolate or strawberry'},
    'imageUrl': '', 'arModelUrl': '', 'isAvailable': True, 'recipe': {},
  },
  {
    'name': 'Bubur Kacang',
    'category': 'Dessert',
    'mealServiceCategory': 'Dessert',
    'price': 4.50, 'costPrice': 1.30, 'targetProfitMargin': 71.1,
    'nutrition': {'calories': 260.0, 'protein': 8.0, 'fiber': 6.0, 'carbs': 46.0, 'fat': 5.0, 'notes': 'Sweet mung bean soup'},
    'imageUrl': '', 'arModelUrl': '', 'isAvailable': True, 'recipe': {},
  },
  {
    'name': 'Kuih Lapis',
    'category': 'Dessert',
    'mealServiceCategory': 'Dessert',
    'price': 3.50, 'costPrice': 1.00, 'targetProfitMargin': 71.4,
    'nutrition': {'calories': 190.0, 'protein': 2.5, 'fiber': 0.5, 'carbs': 35.0, 'fat': 5.0, 'notes': 'Layered steamed kuih'},
    'imageUrl': '', 'arModelUrl': '', 'isAvailable': True, 'recipe': {},
  },
  {
    'name': 'Teh Ais',
    'category': 'Beverage',
    'mealServiceCategory': 'Dessert',
    'price': 3.50, 'costPrice': 0.70, 'targetProfitMargin': 80.0,
    'nutrition': {'calories': 95.0, 'protein': 1.5, 'fiber': 0.0, 'carbs': 20.0, 'fat': 1.5, 'notes': 'Iced milk tea'},
    'imageUrl': '', 'arModelUrl': '', 'isAvailable': True, 'recipe': {},
  },
  {
    'name': 'Coconut Jelly',
    'category': 'Dessert',
    'mealServiceCategory': 'Dessert',
    'price': 5.00, 'costPrice': 1.50, 'targetProfitMargin': 70.0,
    'nutrition': {'calories': 160.0, 'protein': 2.0, 'fiber': 0.5, 'carbs': 30.0, 'fat': 4.0, 'notes': 'Set in coconut shell'},
    'imageUrl': '', 'arModelUrl': '', 'isAvailable': True, 'recipe': {},
  },
  {
    'name': 'Waffles with Ice Cream',
    'category': 'Dessert',
    'mealServiceCategory': 'Dessert',
    'price': 10.00, 'costPrice': 4.00, 'targetProfitMargin': 60.0,
    'nutrition': {'calories': 580.0, 'protein': 9.0, 'fiber': 1.5, 'carbs': 74.0, 'fat': 26.0, 'notes': 'Belgian waffle with 2 scoops'},
    'imageUrl': '', 'arModelUrl': '', 'isAvailable': True, 'recipe': {},
  },
]

menu_ref = db.collection('menu')
for dish in dishes:
    menu_ref.add(dish)
    print(f"Inserted: {dish['name']}")

print(f"\nDone. {len(dishes)} dishes inserted.")