"""Flask prediction API that loads pre-trained model artifacts.

Training is performed separately by train_models.py. Restarting this API does
not retrain any model and does not read the whole Firestore orders collection.
"""

from __future__ import annotations

import datetime as dt
import os
from pathlib import Path
from typing import Any

import joblib
import numpy as np
import pandas as pd
from catboost import CatBoostRegressor
from flask import Flask, jsonify, request
from flask_cors import CORS
from prophet.serialize import model_from_json

from feature_engineering import (
    CATEGORICAL_FEATURES,
    ForecastOverrides,
    build_future_feature_row,
)
from model_utils import load_json

ROOT = Path(__file__).resolve().parent
MODELS_DIR = ROOT / "models"

app = Flask(__name__)
CORS(app)


class ModelRegistry:
    def __init__(self) -> None:
        self.config: dict[str, Any] = {}
        self.metrics: dict[str, Any] = {}
        self.models: dict[str, Any] = {}
        self.load_error: str | None = None
        self._load()

    def _load(self) -> None:
        try:
            self.config = load_json(MODELS_DIR / "feature_config.json")
            self.metrics = load_json(MODELS_DIR / "model_metrics.json")

            paths = {
                "linear_regression": MODELS_DIR / "linear_regression.joblib",
                "xgboost": MODELS_DIR / "xgboost_pipeline.joblib",
                "arima": MODELS_DIR / "arima.joblib",
            }
            for name, path in paths.items():
                if path.exists():
                    # Load only model files generated by your own training script.
                    self.models[name] = joblib.load(path)

            catboost_path = MODELS_DIR / "catboost.cbm"
            if catboost_path.exists():
                cat_model = CatBoostRegressor()
                cat_model.load_model(str(catboost_path))
                self.models["catboost"] = cat_model

            prophet_path = MODELS_DIR / "prophet_model.json"
            if prophet_path.exists():
                self.models["prophet"] = model_from_json(
                    prophet_path.read_text(encoding="utf-8")
                )

            if not self.models:
                raise FileNotFoundError(
                    "No trained model files were found. Run `python train_models.py` first."
                )
        except Exception as error:
            self.load_error = str(error)
            print(f"[ML] Model loading failed: {error}")
        else:
            selected = self.selected_model
            print(
                f"[ML] Loaded {len(self.models)} model(s). "
                f"Selected model: {selected}."
            )

    @property
    def ready(self) -> bool:
        return self.load_error is None and bool(self.models)

    @property
    def selected_model(self) -> str:
        selected = str(self.metrics.get("selected_model", ""))
        if selected in self.models:
            return selected

        candidates = self.metrics.get("models", {})
        successful = {
            name: data
            for name, data in candidates.items()
            if name in self.models
            and data.get("status") == "ok"
            and data.get("mae") is not None
        }
        if successful:
            return min(successful, key=lambda name: float(successful[name]["mae"]))
        return next(iter(self.models))


REGISTRY = ModelRegistry()


def _optional_float(name: str, minimum: float | None = None) -> float | None:
    raw = request.args.get(name)
    if raw is None or raw.strip() == "":
        return None
    try:
        value = float(raw)
    except ValueError as error:
        raise ValueError(f"{name} must be numeric.") from error
    if minimum is not None and value < minimum:
        raise ValueError(f"{name} must be at least {minimum}.")
    return value


def _optional_bool_int(name: str) -> int | None:
    raw = request.args.get(name)
    if raw is None or raw.strip() == "":
        return None
    normalised = raw.strip().lower()
    if normalised in {"1", "true", "yes"}:
        return 1
    if normalised in {"0", "false", "no"}:
        return 0
    raise ValueError(f"{name} must be true/false or 1/0.")


def _request_overrides() -> ForecastOverrides:
    promotion_active = _optional_bool_int("promotion_active")
    promotion_rate = None if promotion_active is None else float(promotion_active)
    weather = request.args.get("weather_condition")
    return ForecastOverrides(
        promotion_rate=promotion_rate,
        special_event=_optional_bool_int("special_event"),
        weather_condition=weather.strip() if weather and weather.strip() else None,
        avg_selling_price=_optional_float("avg_selling_price", minimum=0.0),
        avg_market_price=_optional_float("avg_market_price", minimum=0.0),
        avg_ingredient_cost=_optional_float("avg_ingredient_cost", minimum=0.0),
    )


def _base_history() -> list[float]:
    history = REGISTRY.config.get("history", [])
    values = [float(row["demand"]) for row in history]
    if len(values) < 14:
        raise ValueError("Saved feature history contains fewer than 14 days.")
    return values


def _forecast_ml_model(
    model_name: str,
    start_date: dt.date,
    days: int,
    overrides: ForecastOverrides,
) -> list[float]:
    model = REGISTRY.models[model_name]
    history = _base_history()
    defaults = REGISTRY.config["defaults"]
    forecasts: list[float] = []

    for offset in range(days):
        date = pd.Timestamp(start_date + dt.timedelta(days=offset))
        row = build_future_feature_row(date, history, defaults, overrides)
        if model_name == "catboost":
            row[CATEGORICAL_FEATURES] = row[CATEGORICAL_FEATURES].astype(str)
        prediction = float(model.predict(row)[0])
        prediction = max(0.0, prediction)
        forecasts.append(prediction)
        history.append(prediction)

    return forecasts


def _forecast_model(
    model_name: str,
    start_date: dt.date,
    days: int,
    overrides: ForecastOverrides,
) -> list[float]:
    if model_name in {"linear_regression", "xgboost", "catboost"}:
        return _forecast_ml_model(model_name, start_date, days, overrides)

    if model_name == "arima":
        forecast = np.asarray(REGISTRY.models[model_name].forecast(steps=days), dtype=float)
        return np.maximum(0.0, forecast).tolist()

    if model_name == "prophet":
        dates = pd.date_range(start=pd.Timestamp(start_date), periods=days, freq="D")
        future = pd.DataFrame({"ds": dates})
        forecast = REGISTRY.models[model_name].predict(future)["yhat"].to_numpy(dtype=float)
        return np.maximum(0.0, forecast).tolist()

    raise KeyError(f"Unsupported model: {model_name}")


def _demand_level(prediction: float) -> tuple[str, str]:
    thresholds = REGISTRY.config.get("demand_thresholds", {})
    low_upper = float(thresholds.get("low_upper", prediction))
    high_lower = float(thresholds.get("high_lower", prediction))

    if prediction >= high_lower:
        return (
            "High",
            "High expected menu demand. Consider additional kitchen preparation and staffing.",
        )
    if prediction <= low_upper:
        return (
            "Low",
            "Lower expected menu demand. Normal staffing should be sufficient.",
        )
    return (
        "Moderate",
        "Moderate expected menu demand. Review staffing against reservations and promotions.",
    )


def _rounded(value: float) -> int:
    return max(0, int(round(float(value))))


@app.get("/api/predict")
def predict() -> Any:
    if not REGISTRY.ready:
        return jsonify({"error": REGISTRY.load_error, "status": "models_not_ready"}), 503

    try:
        days = int(request.args.get("days", "7"))
        if not 1 <= days <= 14:
            raise ValueError("days must be between 1 and 14.")
        overrides = _request_overrides()
    except ValueError as error:
        return jsonify({"error": str(error)}), 400

    tomorrow = dt.date.today() + dt.timedelta(days=1)
    forecasts_by_model: dict[str, list[float]] = {}
    failures: dict[str, str] = {}

    for model_name in REGISTRY.models:
        try:
            forecasts_by_model[model_name] = _forecast_model(
                model_name, tomorrow, days, overrides
            )
        except Exception as error:
            failures[model_name] = str(error)
            print(f"[ML] Prediction failed for {model_name}: {error}")

    selected = REGISTRY.selected_model
    if selected not in forecasts_by_model:
        available = [name for name in REGISTRY.models if name in forecasts_by_model]
        if not available:
            return jsonify({"error": "Every model failed during prediction."}), 500
        selected = available[0]

    selected_forecast = forecasts_by_model[selected]
    tomorrow_prediction = selected_forecast[0]
    level, staffing_message = _demand_level(tomorrow_prediction)
    model_metrics = REGISTRY.metrics.get("models", {})
    selected_metrics = model_metrics.get(selected, {})

    week_forecast = [
        {
            "date": (tomorrow + dt.timedelta(days=index)).strftime("%a %d %b"),
            "iso_date": (tomorrow + dt.timedelta(days=index)).isoformat(),
            "demand": _rounded(value),
            # Kept for compatibility with the existing Flutter response parser.
            "orders": _rounded(value),
        }
        for index, value in enumerate(selected_forecast)
    ]

    comparison = {
        name: _rounded(values[0]) for name, values in forecasts_by_model.items()
    }
    estimated_accuracy = {
        name: (
            None
            if details.get("wape") is None
            else round(max(0.0, 100.0 - float(details["wape"])), 1)
        )
        for name, details in model_metrics.items()
        if details.get("status") == "ok"
    }

    result = {
        "predicted_demand": _rounded(tomorrow_prediction),
        # Backward-compatible key. The value represents units, not revenue.
        "predicted_sales": _rounded(tomorrow_prediction),
        "prediction_unit": REGISTRY.config.get("unit", "menu_item_units"),
        "forecast_target": REGISTRY.config.get("target_description"),
        "forecast_date": tomorrow.isoformat(),
        "selected_model": selected,
        "demand_level": level,
        "demand_insight": (
            f"Tomorrow ({tomorrow.strftime('%A, %d %b')}): approximately "
            f"{_rounded(tomorrow_prediction)} menu-item units are predicted "
            f"for one restaurant using {selected}."
        ),
        "staffing_insight": staffing_message,
        "mae": selected_metrics.get("mae"),
        "rmse": selected_metrics.get("rmse"),
        "wape": selected_metrics.get("wape"),
        "r2_score": selected_metrics.get("r2"),
        "data_source": "external_restaurant_sales_dataset",
        "dataset_rows": REGISTRY.config.get("dataset_rows"),
        "daily_rows": REGISTRY.config.get("daily_rows"),
        "models_active": len(forecasts_by_model),
        "week_forecast": week_forecast,
        "model_comparison": comparison,
        "estimated_accuracy_pct": estimated_accuracy,
        "prediction_overrides": {
            "promotion_active": overrides.promotion_rate,
            "special_event": overrides.special_event,
            "weather_condition": overrides.weather_condition,
        },
        "model_failures": failures,
        "warning": (
            "The model was trained on an external dataset. Predictions are prototype "
            "menu-demand estimates, not restaurant-specific customer order counts."
        ),
    }
    return jsonify(result)


@app.get("/api/models")
def models() -> Any:
    if not REGISTRY.ready:
        return jsonify({"error": REGISTRY.load_error}), 503
    return jsonify(REGISTRY.metrics)


@app.get("/health")
@app.get("/")
def health() -> Any:
    status_code = 200 if REGISTRY.ready else 503
    return (
        jsonify(
            {
                "status": "ready" if REGISTRY.ready else "models_not_ready",
                "service": "Smart Restaurant Demand Forecasting API",
                "selected_model": REGISTRY.selected_model if REGISTRY.ready else None,
                "models_loaded": sorted(REGISTRY.models),
                "load_error": REGISTRY.load_error,
            }
        ),
        status_code,
    )


if __name__ == "__main__":
    port = int(os.environ.get("PORT", "5000"))
    app.run(host="0.0.0.0", port=port, debug=False)
