"""Train, compare, save, and select five forecasting models.

Run manually from the project root:
    python train_models.py

The Flask API does not retrain models. It only loads the artifacts generated by
this script.
"""

from __future__ import annotations

import argparse
import importlib.metadata
import platform
import warnings
from pathlib import Path
from typing import Any, Callable

import joblib
import numpy as np
import pandas as pd
from catboost import CatBoostRegressor
from prophet import Prophet
from prophet.serialize import model_to_json
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from statsmodels.tsa.arima.model import ARIMA
from xgboost import XGBRegressor

from feature_engineering import (
    CATEGORICAL_FEATURES,
    MODEL_FEATURES,
    NUMERIC_FEATURES,
    TARGET_COLUMN,
    calculate_defaults,
    load_raw_dataset,
    prepare_training_frame,
)
from model_utils import regression_metrics, save_json

ROOT = Path(__file__).resolve().parent
DEFAULT_DATASET = ROOT / "datasets" / "restaurant_sales_data.csv"
MODELS_DIR = ROOT / "models"
RANDOM_SEED = 42


def package_version(name: str) -> str | None:
    try:
        return importlib.metadata.version(name)
    except importlib.metadata.PackageNotFoundError:
        return None


def make_preprocessor(scale_numeric: bool) -> ColumnTransformer:
    numeric_transformer: Any = StandardScaler() if scale_numeric else "passthrough"
    return ColumnTransformer(
        transformers=[
            ("numeric", numeric_transformer, NUMERIC_FEATURES),
            (
                "categorical",
                OneHotEncoder(handle_unknown="ignore", sparse_output=True),
                CATEGORICAL_FEATURES,
            ),
        ],
        remainder="drop",
    )


def train_linear(
    x_train: pd.DataFrame,
    y_train: pd.Series,
    x_test: pd.DataFrame,
) -> tuple[Pipeline, np.ndarray]:
    model = Pipeline(
        steps=[
            ("preprocessor", make_preprocessor(scale_numeric=True)),
            ("regressor", LinearRegression()),
        ]
    )
    model.fit(x_train, y_train)
    return model, np.maximum(0.0, model.predict(x_test))


def train_xgboost(
    x_train: pd.DataFrame,
    y_train: pd.Series,
    x_test: pd.DataFrame,
) -> tuple[Pipeline, np.ndarray]:
    model = Pipeline(
        steps=[
            ("preprocessor", make_preprocessor(scale_numeric=False)),
            (
                "regressor",
                XGBRegressor(
                    objective="reg:squarederror",
                    n_estimators=500,
                    learning_rate=0.03,
                    max_depth=5,
                    min_child_weight=3,
                    subsample=0.9,
                    colsample_bytree=0.9,
                    reg_alpha=0.0,
                    reg_lambda=1.0,
                    random_state=RANDOM_SEED,
                    n_jobs=2,
                    tree_method="hist",
                ),
            ),
        ]
    )
    model.fit(x_train, y_train)
    return model, np.maximum(0.0, model.predict(x_test))


def train_catboost(
    x_train: pd.DataFrame,
    y_train: pd.Series,
    x_test: pd.DataFrame,
) -> tuple[CatBoostRegressor, np.ndarray]:
    train_frame = x_train.copy()
    test_frame = x_test.copy()
    train_frame[CATEGORICAL_FEATURES] = train_frame[CATEGORICAL_FEATURES].astype(str)
    test_frame[CATEGORICAL_FEATURES] = test_frame[CATEGORICAL_FEATURES].astype(str)

    model = CatBoostRegressor(
        iterations=500,
        depth=6,
        learning_rate=0.03,
        loss_function="RMSE",
        random_seed=RANDOM_SEED,
        verbose=False,
        allow_writing_files=False,
        thread_count=2,
    )
    model.fit(train_frame, y_train, cat_features=CATEGORICAL_FEATURES)
    return model, np.maximum(0.0, model.predict(test_frame))


def evaluate_arima(
    y_train: pd.Series,
    y_test: pd.Series,
) -> tuple[ARIMA, np.ndarray]:
    # A compact weekly-aware order. The model is a baseline; it is not assumed
    # to be the final winner.
    fitted = ARIMA(
        y_train.astype(float).to_numpy(),
        order=(7, 1, 1),
        enforce_stationarity=False,
        enforce_invertibility=False,
    ).fit()
    predictions = np.maximum(0.0, np.asarray(fitted.forecast(steps=len(y_test))))
    return fitted, predictions


def build_prophet() -> Prophet:
    model = Prophet(
        weekly_seasonality=True,
        yearly_seasonality=False,
        daily_seasonality=False,
        seasonality_mode="additive",
        changepoint_prior_scale=0.05,
    )
    model.add_seasonality(name="monthly", period=30.5, fourier_order=5)
    return model


def evaluate_prophet(
    dates_train: pd.Series,
    y_train: pd.Series,
    dates_test: pd.Series,
) -> tuple[Prophet, np.ndarray]:
    model = build_prophet()
    prophet_train = pd.DataFrame(
        {"ds": pd.to_datetime(dates_train).dt.tz_localize(None), "y": y_train.to_numpy()}
    )
    model.fit(prophet_train)
    future = pd.DataFrame({"ds": pd.to_datetime(dates_test).dt.tz_localize(None)})
    predictions = np.maximum(0.0, model.predict(future)["yhat"].to_numpy())
    return model, predictions


def train_and_save(dataset_path: Path, test_fraction: float) -> None:
    MODELS_DIR.mkdir(parents=True, exist_ok=True)

    print(f"[ML] Loading dataset: {dataset_path}")
    raw = load_raw_dataset(dataset_path)
    daily, frame = prepare_training_frame(raw)

    split_index = int(len(frame) * (1.0 - test_fraction))
    if split_index < 60 or len(frame) - split_index < 30:
        raise ValueError(
            "The chronological split must leave at least 60 training rows and 30 test rows."
        )

    train = frame.iloc[:split_index].copy()
    test = frame.iloc[split_index:].copy()
    x_train = train[MODEL_FEATURES]
    y_train = train[TARGET_COLUMN].astype(float)
    x_test = test[MODEL_FEATURES]
    y_test = test[TARGET_COLUMN].astype(float)

    results: dict[str, dict[str, Any]] = {}
    trained: dict[str, Any] = {}

    trainers: list[
        tuple[str, Callable[[], tuple[Any, np.ndarray]]]
    ] = [
        ("linear_regression", lambda: train_linear(x_train, y_train, x_test)),
        ("xgboost", lambda: train_xgboost(x_train, y_train, x_test)),
        ("catboost", lambda: train_catboost(x_train, y_train, x_test)),
        ("arima", lambda: evaluate_arima(y_train, y_test)),
        (
            "prophet",
            lambda: evaluate_prophet(train["date"], y_train, test["date"]),
        ),
    ]

    for name, trainer in trainers:
        print(f"[ML] Training {name}...")
        try:
            model, predictions = trainer()
            metrics = regression_metrics(y_test.to_numpy(), predictions)
            results[name] = {
                "status": "ok",
                **metrics,
            }
            trained[name] = model
            print(
                f"[ML] {name} | MAE={metrics['mae']} | "
                f"RMSE={metrics['rmse']} | WAPE={metrics['wape']}%"
            )
        except Exception as error:  # Keep other models trainable if one fails.
            results[name] = {"status": "failed", "error": str(error)}
            print(f"[ML] {name} failed: {error}")

    successful = {
        name: metrics
        for name, metrics in results.items()
        if metrics.get("status") == "ok" and metrics.get("mae") is not None
    }
    if not successful:
        raise RuntimeError("All model-training attempts failed.")

    winner = min(successful, key=lambda name: float(successful[name]["mae"]))
    print(f"[ML] Winning model: {winner} (lowest chronological test MAE)")

    # Refit each successful model using all engineered rows before persistence.
    x_full = frame[MODEL_FEATURES]
    y_full = frame[TARGET_COLUMN].astype(float)

    if "linear_regression" in trained:
        final_linear, _ = train_linear(x_full, y_full, x_full.iloc[-1:])
        joblib.dump(final_linear, MODELS_DIR / "linear_regression.joblib")

    if "xgboost" in trained:
        final_xgb, _ = train_xgboost(x_full, y_full, x_full.iloc[-1:])
        joblib.dump(final_xgb, MODELS_DIR / "xgboost_pipeline.joblib")

    if "catboost" in trained:
        final_cat, _ = train_catboost(x_full, y_full, x_full.iloc[-1:])
        final_cat.save_model(str(MODELS_DIR / "catboost.cbm"))

    if "arima" in trained:
        final_arima = ARIMA(
            daily[TARGET_COLUMN].astype(float).to_numpy(),
            order=(7, 1, 1),
            enforce_stationarity=False,
            enforce_invertibility=False,
        ).fit()
        joblib.dump(final_arima, MODELS_DIR / "arima.joblib")

    if "prophet" in trained:
        final_prophet = build_prophet()
        final_prophet.fit(
            pd.DataFrame(
                {
                    "ds": pd.to_datetime(daily["date"]).dt.tz_localize(None),
                    "y": daily[TARGET_COLUMN].astype(float).to_numpy(),
                }
            )
        )
        (MODELS_DIR / "prophet_model.json").write_text(
            model_to_json(final_prophet), encoding="utf-8"
        )

    defaults = calculate_defaults(daily)
    history_tail = daily.sort_values("date").tail(60)
    demand_values = daily[TARGET_COLUMN].astype(float)
    low_threshold = float(demand_values.quantile(0.33))
    high_threshold = float(demand_values.quantile(0.67))

    metrics_payload = {
        "selected_model": winner,
        "selection_metric": "mae",
        "target": "average daily menu-item units per active restaurant",
        "unit": "menu_item_units",
        "test_start": str(pd.Timestamp(test["date"].iloc[0]).date()),
        "test_end": str(pd.Timestamp(test["date"].iloc[-1]).date()),
        "training_rows": int(len(train)),
        "test_rows": int(len(test)),
        "total_engineered_rows": int(len(frame)),
        "models": results,
    }
    save_json(MODELS_DIR / "model_metrics.json", metrics_payload)

    config_payload = {
        "dataset_file": dataset_path.name,
        "dataset_rows": int(len(raw)),
        "daily_rows": int(len(daily)),
        "date_start": str(pd.Timestamp(daily["date"].min()).date()),
        "date_end": str(pd.Timestamp(daily["date"].max()).date()),
        "target_column": TARGET_COLUMN,
        "target_description": "Average total quantity sold per active restaurant per day",
        "unit": "menu_item_units",
        "model_features": MODEL_FEATURES,
        "numeric_features": NUMERIC_FEATURES,
        "categorical_features": CATEGORICAL_FEATURES,
        "defaults": defaults,
        "history": [
            {
                "date": str(pd.Timestamp(row.date).date()),
                "demand": round(float(row.daily_demand), 6),
            }
            for row in history_tail.itertuples(index=False)
        ],
        "demand_thresholds": {
            "low_upper": round(low_threshold, 4),
            "high_lower": round(high_threshold, 4),
        },
        "python_version": platform.python_version(),
        "package_versions": {
            "pandas": package_version("pandas"),
            "numpy": package_version("numpy"),
            "scikit-learn": package_version("scikit-learn"),
            "statsmodels": package_version("statsmodels"),
            "prophet": package_version("prophet"),
            "xgboost": package_version("xgboost"),
            "catboost": package_version("catboost"),
            "joblib": package_version("joblib"),
        },
    }
    save_json(MODELS_DIR / "feature_config.json", config_payload)

    print(f"[ML] Saved artifacts to: {MODELS_DIR}")
    print("[ML] Training is complete. Start the API with: python app.py")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dataset",
        type=Path,
        default=DEFAULT_DATASET,
        help=f"CSV path (default: {DEFAULT_DATASET})",
    )
    parser.add_argument(
        "--test-fraction",
        type=float,
        default=0.20,
        help="Latest chronological fraction reserved for testing (default: 0.20).",
    )
    return parser.parse_args()


if __name__ == "__main__":
    warnings.filterwarnings("ignore", category=FutureWarning)
    arguments = parse_args()
    if not 0.10 <= arguments.test_fraction <= 0.35:
        raise ValueError("--test-fraction must be between 0.10 and 0.35.")
    train_and_save(arguments.dataset.resolve(), arguments.test_fraction)
